---
- name: install sudo
  ansible.builtin.package:
    name: [sudo]
    state: present

- name: sudoers.d directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: set sudo configuration
  ansible.builtin.template:
    src: templates/sudoers.j2
    dest: /etc/sudoers
    mode: "0440"
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s

- name: enable ssh pipelining
  ansible.builtin.set_fact:
    ansible_ssh_pipelining: true
